# Generated by Django 4.2 on 2025-07-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('guardian_email', models.EmailField(max_length=254)),
                ('weather_condition', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('ai_message', models.TextField(blank=True)),
                ('safety_recommendation', models.CharField(blank=True, max_length=200)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_awareness',
                'ordering': ['-created_at'],
            },
        ),
    ]
